export const IMG = {
  main: {
    background: "/img/main/main_bg.webp",
  },
    ui: {
      leftPhone: "/img/ui/hand_left_phone.png",
      rightLantern: "/img/ui/hand_right_lantern.png",
      duckpickLogo: "/img/ui/icon-192.png",
    },
  
    object: {
      object01: "/img/object/object01.png",
      object02: "/img/object/object02.png",
      object03: "/img/object/object03.png",
      object04: "/img/object/object04.png",
      object05: "/img/object/object05.png",
      object06: "/img/object/object06.png",
      object07: "/img/object/object07.png",
      object08: "/img/object/object08.png",
      object09: "/img/object/object09.png",
      object10: "/img/object/object10.png",
      object11: "/img/object/object11.png",
      object12: "/img/object/object12.png",
      object13: "/img/object/object13.png",
      object14: "/img/object/object14.png",
      object15: "/img/object/object15.png",
      object16: "/img/object/object16.png",
      object17: "/img/object/object17.png",
      object18: "/img/object/object18.png",
      object19: "/img/object/object19.png",
      object20: "/img/object/object20.png",
      object21: "/img/object/object21.png",
      object22: "/img/object/object22.png",
      object23: "/img/object/object23.png",
      object24: "/img/object/object24.png",
      object25: "/img/object/object25.png",
      object26: "/img/object/object26.png",
      object27: "/img/object/object27.png",
      object28: "/img/object/object28.png",
      object29: "/img/object/object29.png",
      object30: "/img/object/object30.png",
      object31: "/img/object/object31.png",
      object32: "/img/object/object32.png",
      object33: "/img/object/object33.png",
      object34: "/img/object/object34.png",
      object35: "/img/object/object35.png",
      object36: "/img/object/object36.png",
    },
    event: {
      duckpickDoll: "/img/object/object_duckpick_doll.png",
    },
  }